### PR TITLE
supabase migration + new login

### LINKED ISSUE #41: migrate obsidian plugin to use supabase-js
- use [supabase-js](https://www.npmjs.com/package/@supabase/supabase-js) SDK to retrieve and get notes. If the library doesn't work then we will probably need to use the supabase API (talk to me about this after you discover it doesn't work)
  - for [ref](https://github.com/fleetingnotes/fleeting-notes-payments) using the SDK
- have an authentication screen (similar to the Fleeting Notes app in the settings)

## keep in mind
- we may need to refactor the code you write into an SDK so other developers can have an easy way to access their Fleeting Notes.
- could be useful for sharing code between plugins (e.g. Logseq plugin, Tana plugin)

### LINKED ISSUE #43: One way sync with delete from FN not working
Using FN via Mac Chrome extension and iOS app.

Notes sync with Obsidian but do not delete from FN.

### LINKED ISSUE #45: In Spanish the synchronized text becomes unreadable.
I write in Spanish, in which there is the letter "eñe" and some vowels use accents: á, é, í, ó, ú. When I do it this way, when I synchronize Fleeting Notes it changes the text and replaces the eñes and accents with strange characters of this type: ÃÂ¡, ÃÂ³, ÃÂº, ÃÂ±. With this, a well-written text in Spanish becomes illegible. I would be grateful for a solution to this problem.

### PR DESCRIPTION
**Pull request by ransurf**
Closes #41 
Closes #45 
Closes #43

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -22,38 +40,60 @@ export function throwError(e: any, errMessage: string) {
...
+		if (!firebaseId) {
+			throwError(
+				"Fleeting Notes Sync Failed - Please Log In",
+				"Fleeting Notes Sync Failed - Please Log In"
 			);
 		}
+		await supabase
+			.from("notes")
+			.select()
+			.filter("_partition", "eq", firebaseId)
```
Comment (matthewwong525) [inline src/utils.ts:80]: Add another _partition for userId, not just firebaseId, see what i did in `supabase.dart`. Probably something like:
```
.filter("_partition", "in", [firebaseId, supabaseId])
```

Comment (matthewwong525) [reply src/utils.ts:80]: doing this bc in the future we want to move away from firebaseId

**Comment by ransurf** [comment]
Closes #42
